version: "3.1"
services:

    db:
      image: mysql
      container_name: database
      volumes:
        - ./src:/var/www/html
        - ./data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=test
        - MYSQL_DATABASE=test
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test

    php:
      build: ./docker/php/
      container_name: php
      volumes:
          - ./src:/var/www/html
      ports:
       - "5000:80"
      links:
       - db

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=localhost
        - PMA_PORT=3306
      restart: always
      ports:
       - 5050:80

