version: "3.1"
services:

    db:
      image: mysql
      volumes:
        - ./src:/var/www/html
        - ./data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=test
        - MYSQL_DATABASE=test
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test

    php:
      build: ./docker/php/
      volumes:
          - ./src:/var/www/html
      ports:
       - "5000:80"
      links:
       - db

