version: '3'
services:

  php:
    container_name: PHP
    build: ./docker/php/
    volumes:
      - ./docker/php/php.ini://local/etc/php/php.ini:ro
      - ./app:/var/www/app
    working_dir: /var/www/app
    links:
      - db

  webserver:
    container_name: nginx
    image: nginx:1.11
    depends_on:
      - php
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 5080:80

  db:
    image: mysql
    container_name: mySQL
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test

  composer:
    container_name: Composer1.4
    image: composer:1.4
    working_dir: /var/www/YOUR_PROJECT_NAME
